---
title: "p8105_hw5_xc2473"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)

set.seed(10)

iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species))
```

####Problem 1

```{r}
filling = function(x) {
  
  if (is.numeric(x)) {
    x[is.na(x)] = mean(x, na.rm = TRUE)

  }else if (!is.numeric(x)) {
     x[is.na(x)] = "virginica" 
    }
    
  x
}

output1 = map_dfr(iris_with_missing, filling)
```

####Problem 2

```{r}
l = list.files("./data/")

l

readfile = function(filename) {

  r = read_csv(file = paste0("./data/", filename), col_types = cols())
  
  r
}

output2 = purrr::map_dfr(l, readfile)
```

####Problem 3

```{r}

library(broom)

sim_regression = function(beta1, n = 30, beta0 = 2, variance = 50) {
  
  sim_data = tibble(
    xi1 = rnorm(n, mean = 0, sd = 1),
    ϵi = rnorm(n, 0, variance),
    yi = beta0 + beta1 * xi1 + ϵi
  )
  
 ls_fit = lm(yi ~ xi1, data = sim_data)
 
 broom::tidy(ls_fit)
 
}

 

sim_power = 
  sim_results %>% 
  mutate(rejected = ifelse(p.value <= 0.05, 1, 0)) %>% 
  group_by(beta1) %>% 
  summarize(power = mean(rejected))
  
sim_power %>% 
  ggplot(aes(x = beta1 , y = power)) + 
  geom_point() +
  geom_line() +
  labs(
    y = "Power (proportion of times the null was rejected)"
  )


sim_beta1_hat_among_rejected =
  sim_results %>% 
  filter(p.value <= 0.05) %>% 
  group_by(beta1) %>% 
  summarize(mean_estimate = mean(estimate))
  

sim_beta1_hat %>% 
  ggplot(aes(x = beta1, y = mean_estimate)) + 
  geom_point() +
  geom_line() +
  labs(
    y = "the average estimate of beta1",
    caption = "the average estimate of beta 1 only in samples for which the null was rejected"
  )

sim_beta1_hat_among_rejected %>% 
  ggplot(aes(x = beta1, y = mean_estimate)) + 
  geom_point() +
  geom_line() +
  labs(
    y = "the average estimate of beta1",
    caption = "the average estimate of beta 1 only in samples for which the null was rejected"
  )

```

